### ISSUE TITLE
Search seems to prefer longest option first instead of shortest option first

### ISSUE THREAD

**Issue by darloth** [theripper93/spotlight-omnisearch#2]
Playing Pathfinder 2e, I run a search for "Wall of Fi", and I get:

![image](https://github.com/theripper93/spotlight-omnisearch/assets/8480048/b8e2a4c0-687c-45a2-9f3e-2fbd48b7179e)

Obviously it -knows- about Wall of Fire, but it's at the bottom of the list.  The top, and thus default option, is an audio credit inside some sort of journal, I think from an adventure module.

Same with Fireball, it brings back Wand of Fireballs, Necklace of Fireballs, etc, and then finally the Fireball spell at (near) the bottom.

![image](https://github.com/theripper93/spotlight-omnisearch/assets/8480048/6d9e63e4-3bad-4071-862a-3737ca8a9f64)

I think the smallest result that can match should be displayed first.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
