### ISSUE TITLE
Cant Play Playlist in compendium thanks with Dig Down

### ISSUE THREAD

**Issue by Lifthraser** [theripper93/spotlight-omnisearch#3]
Thanks to dig down you can make playlists in compendium appear in omnisearch result, the "play playlist" button does appear but when clicked does not trigger the playlist playing.
In the exemple bellow the first result is from inside the world and plays nicely, but the second result in a compendium, does not plays
![image](https://github.com/user-attachments/assets/8242ae02-47d4-4c1e-935e-51aea250a1a4)

Foundry core, systems, and modules are up to date

Versions:
Foundry: 12 Build 331
Systems: 
- Dungeon World 1.8.2
- Simple World-Building 0.8.2
Modules
- Spotlight Omnisearch 2.0.4
- Dig DOwn - Advanced Search : 3.0.3

Thanks for your awesome modules.

**Comment by theripper93** [comment]
This has nothing to do with dig down, that search will work the same without it. Playlists in compendiums cannot be played. the only bug here is that the play button should not be present in compendium playlists

**Comment by Lifthraser** [comment]
The button is gone, at least now it's clear.
Thank you!
